#!/bin/sh

if [ $# -eq 0 ]
then
    echo '[fail] no parameters are given' >&2
    exit -1
else 
    colno=`expr $1 - 1`
    if [ $? -ne 0 ] || [ $1 -lt 2 ];
    then
        echo '[fail] columns number must be more than 1' >&2
        exit -1
    fi
fi


echo "[success] start to generate HTML" >&2

echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">"
echo "<html>"
echo "  <head>"
echo "    <title>Pictures</title>"
echo "  </head>"
echo "  <body>"
echo "    <h1>Pictures</h1>"
echo "    <table>"

int=0
for pic in $@; do
    if test $int = 0
    then
        colno=$pic
        int=`expr $int + 1`;
    else
        if file --mime-type "$pic" | grep -q jpeg$; then
            if test `expr $int % $colno` = 1; then
            echo "      <tr>"  
            fi

            echo "        <td><img src=\"$pic\" height=100></td>"

            if test `expr $int % $colno` = 0; then
                echo "      </tr>"  
            fi
            int=`expr $int + 1`;
        else
            echo "[fail] $pic is not a jpeg file" >&2 
        fi    
    fi
done

if [ $int -gt 1 ] && test `expr $int % $colno` != 1; then
        echo "      </tr>"  
fi

echo "    </table>"
echo "  </body>"
echo "</html>"

exit 0